$(arg prefix)gen3_lite_2f_gripper_controller:
    # type: position_controllers/GripperActionController
    type: position_controllers/GazeboGripperActionController
    joint: $(arg prefix)right_finger_bottom_joint
    # action_monitor_rate: 100
    goal_tolerance: 0.05 # 0.1                                      # Goal tolerance in radians
    stall_position_threshold: 0.05 # Tune to fit your robot  # Arm is stalling if position (radians) hasn't moved over the threshold
    stall_timeout: 0.5                                     # Arm has stalled if timeout (seconds) is reached
    action_monitor_rate: 10 
    gains:
        $(arg prefix)right_finger_bottom_joint: {p: 10.0, i: 0.0, d: 0.0}

gazebo_ros_control:
  pid_gains:
        $(arg prefix)right_finger_bottom_joint: {p: 10.0, i: 0.0, d: 0.0} 
        $(arg prefix)right_finger_tip_joint: {p: 1.0, i: 0.0, d: 0.0} 
        $(arg prefix)left_finger_bottom_joint: {p: 10.0, i: 0.0, d: 0.0} 
        $(arg prefix)left_finger_tip_joint: {p: 1.0, i: 0.0, d: 0.0}